---
title: "GWAS parameters"
output: html_document
date: "2024-08-29"
---

* **VCF file**: Variant Call Format (VCF) is a standard file format to store genetic variant information. The genotype (GT) data within the VCF is required for the analysis in this tab. For more details about the VCF format, see [this document](https://samtools.github.io/hts-specs/VCFv4.2.pdf).

* **Passport file**: A comma-separated values (CSV) file containing individual names (Sample_ID) in the first column and phenotype values in the subsequent columns. The phenotype column names should correspond to the phenotype ID. Example:

<center>

|Sample_ID | Sepal.Length| Sepal.Width| Petal.Length| Petal.Width|Species |
|:---------:|:------------:|:-----------:|:------------:|:-----------:|:-------:|
|Sample_1  |          5.1|         3.5|          1.4|         0.2|setosa  |
|Sample_2  |          4.9|         3.0|          1.4|         0.2|setosa  |
|Sample_3  |          4.7|         3.2|          1.3|         0.2|setosa  |
|Sample_4  |          4.6|         3.1|          1.5|         0.2|setosa  |
|Sample_5  |          5.0|         3.6|          1.4|         0.2|setosa  |
|Sample_6  |          5.4|         3.9|          1.7|         0.4|setosa  |

</center>

&nbsp;

* **Species Ploidy**: Specifies the ploidy level of the species. The current analysis supports both diploids and autopolyploids.

* **Significance Threshold Method**: Define the method to be used. The ones currently available in GWASpoly are: "M.eff","Bonferroni","FDR","permute". Description contained in GWASpoly package: "The default method, "M.eff", is a Bonferroni-type correction but using an effective number of markers that accounts for LD between markers (Moskvina and Schmidt, 2008). The FDR method is based on version 1.30.0 of the qvalue package."

* **Select Trait**: Once the **Passport file** is uploaded, BIGapp updates this box with the phenotype column IDs. Select the target phenotype to be evaluated. Currently, BIGapp allows selecting only one phenotype at a time.

* **Select Fixed Effects (optional)**: Specifies the Phenotype ID of traits with fixed effects that may influence the evaluated trait.

* **Window size (bp)**: Define the window size for the search of significant markers. Only the most significant marker within this region will be returned. We suggest to evaluate the **LD plot** (see Results description) to define the window size parameter.

* **Number of CPU Cores**: Defines the number of CPU cores to be used for the GWAS analysis, enabling faster processing by splitting the workload across multiple cores.

BIGapp uses GWASpoly random polygenic effect to control for population structure. By default, all markers are used to calculate a single covariance matrix (parameter LOCO = FALSE in GWASpoly set.k function). 
 
BIGapp tests the inclusion of principal components as fixed effects (P + K model). For that, the BIC is calculated for models including 1 to 10 of the first principal components and the kinship matrix. In this step, the mixed model for GWAS is fitted using mixed.solve function of rrBLUP. Then, using the estimated parameters, log-likelihood is calculated by using the equation (2) in Kang et al., 2008. Finally, BIC is calculated by using the standard formula (BIC = K * log(N) - 2 * LL). 

