---
title: "Updog_Dosage_Calling_res"
output: html_document
date: "2024-08-29"
---

* **Download VCF file**:  

VCF file generated by function updog2vcf from package BIGr. The function add lines to the VCF header specifying updog and BIGr versions and command line used. Updog information are kept in the INFO fields: 

  * DP: Total Depth 
  * ADS: Depths for the ref and each alt allele in the order listed 
  * BIAS: The estimated allele bias of the SNP from updog 
  * OD: The estimated overdispersion parameter of the SNP from updog 
  * PMC: The estimated proportion of individuals misclassified in the SNP from updog 
 
And in the FORMAT fields: 

  * GT: Genotype, where 1 is the count of alternate alleles 
  * UD: Dosage count of reference alleles from updog, where 0 = homozygous alternate 
  * DP: Read depth 
  * RA: Reference allele read depth 
  * AD: Allelic depths for the ref and alt alleles in the order listed 
  * MPP: Maximum posterior probability for that dosage call from updog 
 
In case model “f1”, “f1pp” selected, the VCF will contain “parent1” and “parent2” as IDs for the parents defined. If “s1”, “s1pp” are selected, the VCF will contain “parent” as the ID for the input parent. 
